# .github/workflows/dev.yml
name: Standalone CLI
on: [push, pull_request]
jobs:
  machineStandalone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run FluidAttacks CLI
        uses: docker://docker.io/fluidattacks/cli:latest
        with:
          args: skims scan ./.github/workflows/config.yaml 
        continue-on-error: true  
      - name: Check for vulnerabilities
        run: |
          if grep -q "Vulnerability" ./Fluid-Attacks-Results.csv; then
            echo "Vulnerabilities detected, failing the job"
            exit 1
          else
            echo "No vulnerabilities detected"
          fi

      - name: Upload scan results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Fluid-Attacks-Results
          path: ./Fluid-Attacks-Results.csv

